<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<div class="row">
				<div class="contact-form-heading"></div>

				<form action="<?php echo $this->getFormAction(); ?>"
					id="zeoContactForm" method="post">
						<?php echo $this->getBlockHtml('formkey')?>
					<div class="contact-form-heading">
						<h2><?php echo $this->__('Contact Us') ?></h2>
						<p><?php echo $this->__('Thank you for contacting us') ?></p>
					</div>
					<div class="form-group">

						<label for="name"><?php echo $this->__('Name') ?></label> <input
							type="text" class="form-control required-entry input-text"
							id="name" name="name"
							placeholder="*<?php echo $this->__('First & Last Name') ?>"
							value="">

					</div>
					<div class="form-group">
						<label for="email"><?php echo $this->__('Email') ?></label> <input
							type="email"
							class="form-control required-entry input-text validate-email"
							id="email" name="email"
							placeholder="*<?php echo $this->__('Email') ?>" value="">

					</div>
					<div class="form-group">
						<label for="telephone"><?php echo $this->__('Telephone') ?></label>
						<input type="text" class="form-control required-entry input-text"
							id="telephone" name="telephone"
							placeholder="*<?php echo $this->__('Telephone') ?>" value="">

					</div>
					<div class="form-group">
						<label for="message"><?php echo $this->__('Message') ?></label>

						<textarea class="form-control required-entry input-text" rows="4"
							placeholder="<?php echo Mage::helper('contacts')->__('* Message') ?>"
							name="message"></textarea>

					</div>
					
					
					<div class="form-group">
						<input type="text" name="hideit" id="hideit" value=""
							style="display: none !important;" /> <input id="submit"
							style="width: 150px;" name="submit" type="submit" value="Send"
							class="btn btn-primary">

					</div>
				</form>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
//<![CDATA[
    var contactForm = new VarienForm('zeoContactForm', true);
//]]>

</script>